### ISSUE TITLE
Support for markdown-it-attrs?

### ISSUE THREAD

**Issue by rauschma** [nagaozen/markdown-it-toc-done-right#25]
The plugin `markdown-it-attrs` lets you set custom IDs like this:

```md
## Some heading {#custom-id}
```

Alas, if I use it together with `markdown-it-toc-done-right`, the custom IDs are only applied to the headings themselves, but not used in the TOC:

```js
var md = require("markdown-it")({
    html: false,
    xhtmlOut: true,
    typographer: true
  })
  .use(require('markdown-it-attrs'))
  .use(require("markdown-it-anchor"), {
    permalink: true,
    permalinkBefore: true,
    permalinkSymbol: '§'
  })
  .use(require("markdown-it-toc-done-right"));

var result = md.render(`
# Title

[[toc]]

## First section {#one}

## Second section {#two}
`.trim());

console.log(result);

/* Output (with a few newlines inserted):
<h1 id="title"><a class="header-anchor" href="#title">§</a> Title</h1>

<nav class="table-of-contents"><ol>
<li><a href="#title"> Title</a><ol>
<li><a href="#first-section"> First section</a></li>
<li><a href="#second-section"> Second section</a></li></ol></li></ol></nav>

<h2 id="one"><a class="header-anchor" href="#one">§</a> First section</h2>
<h2 id="two"><a class="header-anchor" href="#two">§</a> Second section</h2>
*/
```

**Comment by nagaozen** [comment]
According to [Markdown-it architecture](https://github.com/markdown-it/markdown-it/blob/master/docs/architecture.md), block rules are always processed before inline rules. Because one of our reasons to exist was exactly to be a block parser (check README)[https://github.com/nagaozen/markdown-it-toc-done-right/] and also because `markdown-it-attrs` is an inline rule, I don't believe this is achievable without bringing that plugin logic into this one (as we did with the markdown-it-anchor). I'm open to PR though.

**Comment by rauschma** [comment]
Makes sense. Thanks for the reply!

**Comment by rauschma** [comment]
I’ve opened an issue: https://github.com/markdown-it/markdown-it/issues/618#issuecomment-562684784

It really seems like an issue that’s worth being fixed (e.g. by adding an optional second pass), but I don’t know enough of the details to reply properly. Can you help?

**Comment by nagaozen** [comment]
We need to investigate further. For now I agree with @puzrin it's not a `markdown-it` related problem. Maybe observing for an Event from `markdown-it-attrs`, but it doesn't to fire events ...
