### ISSUE TITLE
Compatibility with markdown-it@^11.0.0

### ISSUE THREAD

**Issue by peschee** [nagaozen/markdown-it-toc-done-right#31]
I'm getting this warning when using `markdown-it@^11.0.0` in my `package.json`:

```
warning " > markdown-it-toc-done-right@4.1.0" has incorrect peer dependency "markdown-it@^10.0.0".
```

Are there any issues with `markdown-it@^11.0.0` or could you bump the peer dependency?

**Comment by nagaozen** [comment]
I'm going to take a look after my business hours.

**Comment by nagaozen** [comment]
Made a git clone and updated everything to `latest`. By running tests and checking `tdd.helper.html` it seems to be working fine. I was unable to receive the given warning though. Feel free to re-open with further details.

Because it's working with `^10.0.0`, there's no need to bump the peer dependency.

**Comment by peschee** [comment]
You should get the warning when using yarn. Thanks for the writeup.
