### ISSUE TITLE
Feature Request: Option to link back to TOC from every H2

### ISSUE THREAD

**Issue by jbmilgrom** [nagaozen/markdown-it-toc-done-right#33]
What do you think adding support for a link back to the table of contents from items listed in the TOC, in order to facilitate navigation to and from. I'd be happy to draft a PR if this is something you'd be interested in. Thanks!

**Comment by nagaozen** [comment]
Well, surely going back and forth is a good idea but I'm skeptical that putting a link in every header is right solution. I believe that by just assigning an ID to the table of contents is enough because later you can place eg a fixed anchor at the bottom right of the viewport to go back to the TOC.
