### ISSUE TITLE
placeholder as pattern

### ISSUE THREAD

**Issue by tessus** [nagaozen/markdown-it-toc-done-right#7]
I would like a table of contents creation for the following 4 cases:

```
[toc]
[TOC]
[[toc]]
[[TOC]]
```

Unfortunately the placeholder does not allow to specify a pattern, otherwise I could just use `/^\[{1,2}toc\]{1,2}/im`.

Any chance you could allow the use of a regex pattern?

**Comment by nagaozen** [comment]
No, using regular expression patterns is considered harmful because it makes impossible to fast reject tokens. As pointed out in the README:

> Another very common (C1) mistake that can be found in the wild is using an optional regular expression to match the placeholder in the source, but using a hard-coded charCodeAt value to reject a token.

All libraries that offered this option are, in fact, defective in their implementations. Our recommendation is to choose a placeholder and stick with in the entire database, fixing possible inconsistencies in the process.

**Comment by tessus** [comment]
Ok, then. How about allowing to use an array to specify more than one placeholder? Would that be sufficiently safe?

**Comment by nagaozen** [comment]
It would be better, but this seems to me that you are trying to solve a problem in the wrong layer. Going from a string to an array will increase the complexity of the algorithm with no clear advantage. Really, why supporting so many different placeholders in the same project makes any sense? A `grep | sed` would be enough to solve this kind of inconsistencies. For a plugin, fast behavior is a valuable asset because it's usually working with many other components and while it may seem like a minor issue alone, it can harm you in the big picture.

**Comment by tessus** [comment]
Well, I'm evaluating the use of this plugin for the project Joplin. I cannot say, if it will be included, but I'm sure that people are used to different markers. The ones primarily used are the 4 I mentioned (most available markdown editors either use `[toc]` or `[[toc]]`). That's why.

**Comment by nagaozen** [comment]
Behavior implemented in `3.0.0`. The described cases are built-in and also the Azure DevOps wiki style `[[_toc_]]`.

**Comment by tessus** [comment]
Nice, thank you. So the placeholder variable is obsolete or does it overwrite the default cases? Or does it add to the default cases?

**Comment by nagaozen** [comment]
Its the same option, with backward compatibility. Just augmented to handle extra cases. It's used as a partial pattern which get anchored later. I also had to modify the rejection strategy. Bumped a version because users already using that option will face a compat break
